#!/usr/bin/env python3
"""Demonstration of real model integration flow for Phase 4:

Flow:
GitHub Issue
    ↓
PlannerAgent
    ↓
Plan
    ↓
CoderAgent
    ↓
ModelGateway
    ↓
OllamaClient
    ↓
gpt-oss:20b
    ↓
CodeProposal

Usage:
    python scripts/demo_coder_ollama.py
"""

import json
import sys
from typing import Any, Dict

from harness.agents.coder import CoderAgent
from harness.agents.planner import PlannerAgent
from harness.model.gateway import ModelGateway
from harness.model.ollama import OllamaClient
from harness.model.schemas import CodeProposal, Plan


def main() -> None:
    print("=" * 75)
    print("DEMO: Real Model Integration Flow (Phase 4: Planner -> Coder)")
    print("GitHub Issue -> PlannerAgent -> Plan -> CoderAgent -> ModelGateway -> OllamaClient -> gpt-oss:20b -> CodeProposal")
    print("=" * 75)

    # 1. Incoming GitHub Issue
    issue: Dict[str, Any] = {
        "title": "Add optional tag filtering to GET /items endpoint",
        "description": (
            "Currently GET /items returns all items without filtering. "
            "Users need to filter items by tag (e.g. ?tag=security). "
            "If 'tag' query parameter is provided, return only items that contain the tag. "
            "If no items match, return an empty list with HTTP 200. "
            "Add validation and maintain existing behavior when tag is omitted."
        ),
    }

    repo_info = {
        "tree": "src/\n  api/\n    routes.py\n  services/\n    item_service.py",
        "files": (
            "--- src/api/routes.py ---\n"
            "from typing import List, Optional\n"
            "from fastapi import APIRouter, Query\n"
            "from src.services.item_service import get_items_from_db\n\n"
            "router = APIRouter()\n\n"
            "@router.get('/items')\n"
            "def get_items():\n"
            "    return get_items_from_db()\n\n"
            "--- src/services/item_service.py ---\n"
            "from typing import List, Optional, Dict, Any\n\n"
            "ITEMS = [\n"
            "    {'id': 1, 'name': 'Firewall Appliance', 'tags': ['security', 'hardware']},\n"
            "    {'id': 2, 'name': 'Auth Proxy', 'tags': ['security', 'backend']},\n"
            "    {'id': 3, 'name': 'Web Frontend', 'tags': ['frontend']},\n"
            "]\n\n"
            "def get_items_from_db():\n"
            "    return ITEMS\n"
        ),
        "context": "Python FastAPI microservice with in-memory service layer.",
    }

    print("\n[1] Incoming GitHub Issue:")
    print(f"    Title: {issue['title']}")
    print(f"    Description: {issue['description']}")

    # 2. Setup ModelGateway with OllamaClient (gpt-oss:20b)
    print("\n[2] Instantiating OllamaClient and ModelGateway...")
    client = OllamaClient(
        model_name="gpt-oss:20b",
        base_url="http://localhost:11434/v1",
    )
    gateway = ModelGateway(provider=client)
    print(f"    OllamaClient configured for model: {client.model_name}")

    # 3. PlannerAgent produces Plan
    print("\n[3] Step 1: Running PlannerAgent to generate Plan...")
    planner = PlannerAgent(model=gateway, temperature=0.1)
    plan: Plan = planner.plan(issue=issue, repo_info=repo_info)

    print("\n" + "-" * 70)
    print("PLAN GENERATED BY PLANNER AGENT:")
    print(f"Goal: {plan.goal}")
    print(f"Requirements ({len(plan.requirements)}):")
    for req in plan.requirements:
        print(f"  • {req}")
    print(f"Steps ({len(plan.steps)}):")
    for step in plan.steps:
        print(f"  • {step}")
    print(f"Files to investigate: {plan.files_to_investigate}")
    print("-" * 70)

    # 4. CoderAgent produces CodeProposal from Issue + Plan + Repo Info
    print("\n[4] Step 2: Running CoderAgent with Plan and Repo Context...")
    coder = CoderAgent(model=gateway, temperature=0.2)
    proposal: CodeProposal = coder.code(
        issue=issue,
        plan=plan,
        repo_info=repo_info,
    )

    # 5. Display the resulting CodeProposal
    print("\n" + "=" * 75)
    print("RESULT: Structured CodeProposal Received from CoderAgent")
    print("=" * 75)
    print(f"Type: {type(proposal).__module__}.{type(proposal).__name__}")
    print(f"\nThought Process:\n{proposal.thought_process}\n")
    print(f"Explanation:\n{proposal.explanation}\n")
    print(f"Files to Modify: {proposal.files_to_modify}\n")

    print(f"Proposed Changes ({len(proposal.changes)}):")
    for idx, change in enumerate(proposal.changes, 1):
        print(f"\n--- Change #{idx} ---")
        print(f"File Path:   {change.file_path}")
        print(f"Action:      {change.action}")
        print(f"Explanation: {change.explanation}")
        if change.new_content:
            print(f"New Content:\n```python\n{change.new_content}\n```")
        if change.diff:
            print(f"Diff:\n```diff\n{change.diff}\n```")

    # Assertions / Validations
    assert isinstance(proposal, CodeProposal), f"Expected CodeProposal, got {type(proposal)}"
    assert isinstance(proposal.files_to_modify, list) and len(proposal.files_to_modify) > 0
    assert isinstance(proposal.changes, list) and len(proposal.changes) > 0
    for change in proposal.changes:
        assert change.file_path != ""
        assert change.action in ("modify", "create", "delete")
        assert change.explanation != ""
        assert change.new_content is not None or change.diff is not None

    print("\n[Status]: Full Plan -> Coder flow verified successfully!")


if __name__ == "__main__":
    main()
